### ISSUE TITLE
саня лох 

### ISSUE THREAD

**Issue by rawzoul** [SanyaPilot/IDA_Lab10#1]

**Comment by SanyaPilot** [comment]
![images.jpeg](https://github.com/user-attachments/assets/313dd955-33bf-4d65-86f7-cbf2d88adbc6)

**Comment by Ultra119** [comment]
У меня опять эта проблема

**Comment by rawzoul** [comment]
> У меня опять эта проблема

![Image](https://github.com/user-attachments/assets/fae64990-dd26-4cab-aa27-4b394ba4abc7)
